# docker-compose.production.yml
version: '3'

volumes:

  pg_data_kittygram:
  static_kittygram:
  media_kittygram:

services:

  db:
    image: postgres:13
    container_name: kittygram_db
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data

  backend:
    image: koyote92/kittygram_backend
    container_name: kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/app/media

  frontend:
    image: koyote92/kittygram_frontend
    container_name: kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static

  gateway:
    image: koyote92/kittygram_gateway
    container_name: kittygram_gateway
    env_file: .env
    volumes:
      - static_kittygram:/staticfiles
      - media_kittygram:/app/media
    ports:
      - "9000:80"
